### ISSUE TITLE
`<Button />`を用いたページ遷移で`target="_blank"`が使えない

### ISSUE THREAD

**Issue by youchann** [voyagegroup/ingred-ui#1079]
- 現状対応していない
- https://github.com/mui/material-ui/blob/master/packages/mui-material/src/ButtonBase/ButtonBase.d.ts#L101-L104 MUIだと型だけ見たがうまいことやっていそう

**Comment by Yutan0423** [comment]
https://github.com/voyagegroup/ingred-ui/pull/1410
で対応したのでクローズ
