### ISSUE TITLE
Confirmed modalからアクションボタンを除去したい

### ISSUE THREAD

**Issue by noronaoki** [voyagegroup/ingred-ui#1101]
https://ingred-ui.netlify.app/?path=/story/components-utils-confirmmodal--with-sub-actions
そもそもなぜコンポーネントとしてこのボタンが組み込まれているかはよく分かっていないのが前提としてあるけど。

タイトル横にアクションボタンがセットで実装されているのは柔軟性に欠けるのでできれば除去したい。（別の要素を載せたいって時にそれができないので）

**Comment by youchann** [comment]
`subactions`propsに入るものがReactNode | undefinedになるイメージ。

**Comment by youchann** [comment]
`subactions`部分のheightは任意。大きい要素が入るとそのまま上部の高さが大きくなる。

<img width="444" alt="image" src="https://user-images.githubusercontent.com/40020812/202087336-a8ac8995-5e03-4a41-8438-7e43bce3171b.png">

**Comment by penicillin0** [comment]
@youchann @noronaoki 

このissueのモチベーション的に[tipElement](https://ingred-ui.netlify.app/?path=/story/components-utils-confirmmodal--with-tips)も`ReactNode`として渡す感じにした方が統一感あるのかなと思ったんですが、どうでしょうか
(アクションじゃないものも渡せてしまうので、`subAction`という名前じゃないほうが良い？)

**Comment by takurinton** [comment]
MEMO
tipElement も subAction も一緒で良さそう。

**Comment by takurinton** [comment]
メモ

- 従来の tipElement も subActions の1つとして扱う
  - そのため tipElement prop は削除
- subActions は ReactNode[] を受け取る
  - 1つだけ渡したい場合でも array で渡す
  - 1つ用と2つ以上用の両方の story を作る
- subActions の1つ1つの要素の gap はいじれない
- title と subActions の間の padding はいじれない
