### ISSUE TITLE
<DataTable />テキスト部分でラジオボタンやチェックボックスを制御したい

### ISSUE THREAD

**Issue by youchann** [voyagegroup/ingred-ui#116]
ref: https://github.com/voyagegroup/fluct_datastrap/issues/991

**Comment by yutaro1031** [comment]
- どこで制御したいか(`<tr />`全体?テキストのみ?)

をはっきりして、テキスト部分がリンクとなっている場合の制御をうまくやれば良さそう。

**Comment by youchann** [comment]
現状実装されているのでClose
