### ISSUE TITLE
Storybookv7、addon-consoleがv7未対応

### ISSUE THREAD

**Issue by penicillin0** [voyagegroup/ingred-ui#1228]
### 背景

v7化に伴って使えなくなる
対応issue↓
https://github.com/storybookjs/storybook-addon-console/issues/65

### やること
- このプラグインの必要可否判断
- 必要ない場合 -> 消す
- 必要な場合 -> 代替手段を探す、無かった場合はv7対応状況をwatchしておく

**Comment by takurinton** [comment]
声かけたら対応してくれた
https://github.com/storybookjs/storybook-addon-console/releases/tag/v2.0.0

**Comment by takurinton** [comment]
不要ということで close
