### ISSUE TITLE
colors.basic[300] をpaletteにのせるか検討する

### ISSUE THREAD

**Issue by yutaro1031** [voyagegroup/ingred-ui#129]
よく使う割にはpaletteに乗っていない。

基本的に全ての色はpalette経由で利用者がオーバーライドできるようにするのが良い。

ref: https://github.com/voyagegroup/ingred-ui/pull/126#discussion_r457063054

**Comment by yutaro1031** [comment]
memo

現状の`palette.divider`をbasic[300]に戻して
- msv2のindexページ
- `<MenuList />`で用いられている`<divider />`に当たる部分

↑を`gray.light`にしてしまえば良いのではという話をした。

また、gray周りで似たような悩みが頻繁に起きているので、`palette.gray`だけプロパティを増やすなどの抜本的な改善を考えようという話をした。

**Comment by noronaoki** [comment]
@yutaro1031 こっちのissueで解決できるやつだよね？
https://github.com/voyagegroup/fluct_XDC/issues/45

**Comment by noronaoki** [comment]
ref https://github.com/voyagegroup/ingred-ui/issues/129
