### ISSUE TITLE
`<DataTable />`の`<th />`内の`<Checkbox />`を上下中央寄せで表示する

### ISSUE THREAD

**Issue by youchann** [voyagegroup/ingred-ui#138]
ちょっと上下がずれている
![image](https://user-images.githubusercontent.com/40020812/88626053-ee753100-d0e4-11ea-966f-41e7f738fc0b.png)

**Comment by youchann** [comment]
現状もそうなっている

**Comment by youchann** [comment]
ラジオボタンも同様かもしれない。

**Comment by youchann** [comment]
https://ingred-ui.netlify.app/?path=/story/components-data-display-datatable--selectable-rows

Storybookでいうとこちらのコンポーネント。

**Comment by takurinton** [comment]
https://github.com/voyagegroup/ingred-ui/pull/1097 で直したので完了。
