### ISSUE TITLE
<Icon /> 個別importできるようにする

### ISSUE THREAD

**Issue by kinokoruumu** [voyagegroup/ingred-ui#14]

**Comment by youchann** [comment]
`<TwitterIcon />`とか、個別の命名でimportできるようにしたい意図だと推察

**Comment by youchann** [comment]
Tree shakingできる、あるいはしやすくなる

**Comment by takurinton** [comment]
特に対応する必要なさそう。
やりたくなったらそのタイミングで再度 issue 立てる感じで
