### ISSUE TITLE
コメントアウト等を英語に切り替える

### ISSUE THREAD

**Issue by youchann** [voyagegroup/ingred-ui#152]
1. 使ってくれる人を増やす
2. 海外からのコントリビュートしてくれる人を増やす

両者のためには必要そう。

**Comment by yutaro1031** [comment]
Storybook内のフォントをどう扱うべきか聞いている。
https://cartaholdings.slack.com/archives/CKYAWNNLX/p1613546205387200

**Comment by yutaro1031** [comment]
https://cartaholdings.slack.com/archives/CKYAWNNLX/p1613549047399200

正味使う側でまちまち変わるのでとりあえず`Roboto`か`PT sans`にしてみる

**Comment by yutaro1031** [comment]
↑は一旦そのままにしておく

https://github.com/voyagegroup/ingred-ui/issues/250

**Comment by yutaro1031** [comment]
下記コンポーネントはロジックに影響が出るので別PRで対応
- `<DataTable />`
- `<DatePicker />`
- `<DateRangePicker />`
- `<NavigationRail />`(Footer)
- `<TextField />`

**Comment by yutaro1031** [comment]
なんかmomentでいい感じにやっているところとか、他のコンポーネントをみてる感じだと、`theme`にlocaleの情報を加えて、各箇所に文字列などを当て込んでいく方向のほうが良さそうだな。

**Comment by yutaro1031** [comment]
ちょっと大きくなりそうな気がするけど
- themeにlocaleの情報を入れられるようにする
- 各localeごと、各コンポーネントのごとに文字列などを当てこめる仕組みを作る(この情報すらthemeに入れても良いかも)

あたりをやろうかな

**Comment by youchann** [comment]
https://github.com/voyagegroup/ingred-ui/pull/252#issuecomment-826490718
一旦英語の状態にしておく
