### ISSUE TITLE
navigationRailのExpantionMenuItemのtitleをcontentに置換する

### ISSUE THREAD

**Issue by maktak1995** [voyagegroup/ingred-ui#178]
* Unionを取っている`React.ComponentPropsWithRef<"div">` のPropが `title: string` を持っているため、titleにstring以外を設定できなくなってしまっている
* titleの利用をやめてかわりに独自の `content` という要素を定義して置き換える

ref: https://github.com/voyagegroup/ingred-ui/pull/177

**Comment by youchann** [comment]
`children`の方が良いのかもしれない

**Comment by penicillin0** [comment]
ref: #1090

**Comment by takurinton** [comment]
メモ
