### ISSUE TITLE
<DataTable />内でstateを持たない

### ISSUE THREAD

**Issue by youchann** [voyagegroup/ingred-ui#182]
利用する側(コンポーネント)でも「選択した行」を`state`として持っているので、`state`の二重管理となる。
コードもそのせいで複雑になっている節があるので、`props`で管理したい。

**Comment by yutaro1031** [comment]
行でいうとこの辺をpropsで管理したい。
https://github.com/voyagegroup/ingred-ui/blob/master/src/components/DataTable/DataTable.tsx#L186
