### ISSUE TITLE
破壊的変更にポリシーを持つ

### ISSUE THREAD

**Issue by youchann** [voyagegroup/ingred-ui#186]
何もポリシーを持たないで開発していると、すぐにバージョン`20.0.0`とかになりそう。

他の息の長いライブラリとかを見つつ、その辺のポリシー周りを調べる。

**Comment by yutaro1031** [comment]
@ryokosuge さんがCIまわりをいずれ整えてくれるのでそのタイミングで議論したい

**Comment by youchann** [comment]
https://github.com/voyagegroup/ingred-ui/pull/295 あたりでいい感じに考えられているのでclose

ref: https://docs.google.com/document/d/135NCVM5gxkR7WkQkyjBsC2A219iAXUTHrFW99jQxytg/edit?usp=sharing
