### ISSUE TITLE
<DataTable />のonSelectRowsChangeの参照が変わると無限レンダリングする

### ISSUE THREAD

**Issue by youchann** [voyagegroup/ingred-ui#190]
```tsx
  const [selectedRowIds, setSelectedRowIds] = React.useState<Set<number>>(
    new Set<number>(),
  );

  const onHandleSelectRowsChange = (rowIds: number[]) => {
    setSelectedRowIds(new Set<number>(rowIds));
  };

return (
  <DataTable
    onSelectRowsChange={onHandleSelectRowsChange}
  />
)
```

1. `<DataTable />`内部の`useEffect`で`onSelectRowsChange()`が発火
2. `selectedRowIds`が変更される
3. 再レンダリングの影響で`onHandleSelectRowsChange`の参照が変わる
4. 1に戻る

利用側で`useCallback()`を使えば済む話だが、使わなくても無問題な実装にしたい。

**Comment by yutaro1031** [comment]
そもそも<DataTable />でstateを持たないように努めれば良い気もしている

**Comment by youchann** [comment]
https://github.com/voyagegroup/ingred-ui/issues/182 で解決できる

**Comment by takurinton** [comment]
https://github.com/voyagegroup/ingred-ui/pull/1120 で解決できていそうなので close する。
リリースはまだ。
