### ISSUE TITLE
MenuPropsから`React.ComponentPropsWithRef<"div">`を取り除く

### ISSUE THREAD

**Issue by youchann** [voyagegroup/ingred-ui#211]
#205 の変更で、`menuListProps`が含まれるため、`React.ComponentPropsWithRef<"div">`は不要となる。

**Comment by takurinton** [comment]
コンテキストが少なすぎて issue から推測できないけど、これ必要そうに見える。どうなんだろう。

**Comment by takurinton** [comment]
`menuListProps?.onClick` があるから `rest.onClick` は不要だよってことだろうか。

https://github.com/voyagegroup/ingred-ui/blob/master/src/components/Menu/Menu.tsx#L77

**Comment by penicillin0** [comment]
だとしても`MenuList`は`div`なので、`React.ComponentPropsWithRef<"div">`は欲しい気がする？

**Comment by takurinton** [comment]
@penicillin0 
それは forwardRef のジェネリクスで HTMLDivElement 指定してるから問題ないのでは？div 注釈は入るしこのレイヤーでわざわざ `React.ComponentPropsWithRef<"div">` にする必要なさそう。

**Comment by penicillin0** [comment]
あー`div`相当のPropsは全部`menuListProps`経由で渡せばいい感じですねmm
であれば問題なさそうですね！（rest.onClick が不要だという前提）



(内側の`MenuList`に渡ってるので、`Popover`と分けて渡したいなーって思ったけど、それは #184 でした)

**Comment by takurinton** [comment]
@penicillin0 
> rest.onClickはmenuListProps?.onClickの方で渡してあげることになるので大丈夫そうかな？

うーんここは issue を立てた @youchann に最終的に確認する必要があるけど、おそらく大丈夫だと思う。
これももちろんマイグレーションガイドに書いておくべきではあるけど、パッと見た感じプロダクト側ではこの onClick は指定できなくても現状壊れなさそう。

**Comment by youchann** [comment]
> rest.onClickはmenuListProps?.onClickの方で渡してあげることになるので大丈夫そうかな？


大丈夫です！
