### ISSUE TITLE
多言語対応（i18n）する

### ISSUE THREAD

**Issue by youchann** [voyagegroup/ingred-ui#312]
ref: https://github.com/voyagegroup/ingred-ui/issues/152
ref: https://github.com/voyagegroup/ingred-ui/pull/252#issuecomment-826490718

英語以外の環境で利用すると、各コンポーネントの引数に毎回代入する必要があるので、対応する。

**Comment by kohashi** [comment]
やってみる。
i18nのイメージはこんなかんじ？
material-ui.com/guides/localization/#locale-text

ThemeProvider を経由してロケールの文字列を注入している。

こんなかんじ
```
TablePagination.propTypes = {
   labelRowsPerPage: PropTypes.node,
}
```
https://github.com/mui-org/material-ui/blob/21d0032f54bb765cf65642650ced67d404c37e21/packages/material-ui/src/TablePagination/TablePagination.js#L315-L321



デフォルトの英語版は直接値を代入していて、各ロケールは locale/index.ts で管理してる。 
jaJPはこう。
https://github.com/mui-org/material-ui/blob/0bc3723f148318d78b22939d975e1c4e5cda3380/packages/material-ui/src/locale/index.ts#L1538-L1561

ロケールが絡むのは MuiBreadcrumbs, MuiTablePagination, MuiRating, MuiAutocomplete, MuiAlert, MuiPagination くらいか。少ない。
対応ロケールは多い。39言語。

Material-UIはカレンダー(MuiPickers)のi18nはまた別でやってる。
これは確かに、カレンダーに関してはロケールとはまた別に設定したいケースもあるからかな。。。

**Comment by kohashi** [comment]
```
<ToggleButton
  inActiveText="オフ"
  activeText = "ON"
/>
```

このような代入を、Themeからやるみたいな感じ。

対象が難しいな。ざっくり見た感じ
- ToggleButton: inActiveText, activeText, 
- ConfirmModal: confirmText, cancelText, 
- FileUploader: title, 
- ItemEmpty: title, 

この4コンポーネント 6箇所でのみデフォルト文字列が使われてる感じっ

**Comment by kohashi** [comment]
LocaleProvider って名前でいいかな。
Antはそういうやつだし。
https://2x.ant.design/components/locale-provider/


i18n = 国際化 = 何でも入れられるようにする
l10n = 地域化(マジ？ローカライゼーションの和訳として適切？) = xx国/xx地域に適合させる

だからこれは i18n provider じゃなく、 l10n provider なのだよっていう認識。

**Comment by youchann** [comment]
> やってみる。
i18nのイメージはこんなかんじ？

みてなくて恐縮です:bow:

でもイメージは完全に自分と一致していました:+1:(当時自分もMuiを見てた...)

**Comment by youchann** [comment]
あーカレンダーどうしよう...

**Comment by youchann** [comment]
https://github.com/voyagegroup/ingred-ui/issues/975

残りはカレンダーだけなので、↑で解消されることを期待。

**Comment by takurinton** [comment]
https://github.com/voyagegroup/ingred-ui/pull/1398
