### ISSUE TITLE
Selectでlimitを設定しているとプルダウンメニューが消える

### ISSUE THREAD

**Issue by maktak1995** [voyagegroup/ingred-ui#369]
Selectを利用する際に以前のように `limit` オプションを設定するとプルダウンメニューをフォーカスしたときにオプションの内容が消えるという問題が発生した。

**Comment by youchann** [comment]
そもそもlimitオプションなくしても良い気がしている

**Comment by youchann** [comment]
あるいはいい感じに対応する

**Comment by penicillin0** [comment]
ref: #1090
