### ISSUE TITLE
react-toast-notifications has no longer be maintained. 

### ISSUE THREAD

**Issue by kohashi** [voyagegroup/ingred-ui#439]
> This was a great project to learn from and fulfilled the requirements it set out to. Unfortunately, I can no-longer give this project the time it needs. Consider react-hot-toast as an alternative, or look at the source and make your own 🎉 (there really isn't much to it).

https://github.com/jossmac/react-toast-notifications

https://cartaholdings.slack.com/archives/C018N87TM70/p1630461950051700

**Comment by kohashi** [comment]
純粋に移植しても、MIT License なので表示さえ残せば良い。
https://github.com/jossmac/react-toast-notifications/blob/master/LICENSE

jsx->tsx して、その他色々適合するように変えつつも、ライセンス表記は残す、で良いかな。

**Comment by youchann** [comment]
おー書かれていた、あざますmm

そしてライセンスの事考慮に入れていなかった...流石です:bow:

**Comment by youchann** [comment]
いったん移植できているんでclose
