### ISSUE TITLE
より見やすくする(発見性を上げる)

### ISSUE THREAD

**Issue by kohashi** [voyagegroup/ingred-ui#889]
- readme.md に https://ingred-ui.netlify.app/?path=/story/information-samples--overview へのリンクを載せる
- ファーストビューで color一覧が見える必要はないので、末尾くらいに移す(ファーストビューをLayout/Navigationにする）

**Comment by youchann** [comment]
後々詳細を聞いてみる

**Comment by takurinton** [comment]
- colors のセクションを1番下に移す
- スタイルが当たっていない部分を直す
