### ISSUE TITLE
DatePicker/DateRangePicker のリニューアル

### ISSUE THREAD

**Issue by maktak1995** [voyagegroup/ingred-ui#975]
## 背景
* [momentjs](https://momentjs.com/) がアプデを終了してしばらく経つのでライブラリの切り替えをしようとした
* ingred-ui の DatePicker 系は [react-dates](https://github.com/react-dates/react-dates) を使っているが、この react-dates と momentjs は依存関係にある
* react-dates の脱momentjsは議論されているが一向に進展がないので両方ともライブラリを切り替えることにした
* その過程で DateRangePicker そのものに不満があるという話が上がってきた
* そもそも現状の DateRangePicker が急ごしらえのもので、理想形ではない
* なので理想形のDateRangePickerをフルスクラッチで作る方向ですすめることに

## デザイン
[仕様Doc](https://docs.google.com/document/d/1xCYGOcgtyQfXsAi0Tv_OW1XrdkyDqE8f2hBI87uRIbc/edit#)
DateRangePickerとDatePickerは同じデザインを使う

### momentjs の代わりに dayjs を導入する
  * dayjs は momentjs との後方互換性をもっているため
  * [TC39](https://github.com/tc39/proposal-temporal) の Temporal が仕様として取り込まれた場合、Date オブジェクトが使われなくなる可能性があるので現状では後方互換性を優先してもよいという考え

### react-dates の置き換えは自前の実装で行う
* 新デザインに流用できそうなライブラリが存在しない
* dayjsがまだ若いライブラリなので、DatePicker の wrapperライブラリがまだ少ない
* ざっくりとした実装テストはたくりんとんがすでに実施してくれている
  * [実装に関する記事](https://dev.takurinton.com/tech/frontend/calender-ui-prototype.html)
  * [PR](https://github.com/takurinton/calendar/pull/2)

## 関連issue
* [#871](https://github.com/voyagegroup/ingred-ui/issues/871)
* [#856](https://github.com/voyagegroup/ingred-ui/issues/856)

## 経過進捗
2022/9 まきたけが仕様策定を開始
2022/11 [dayjsをwrapper経由で使うようにする変更](https://github.com/voyagegroup/ingred-ui/pull/1080)をリリース
2022/12 まきたけがDstへの注力と自身の実装力不足を理由にこのタスクから離脱
2022/12 このタスクの補助をよくしてくれていたたくりんとんが後を引き継ぐ

**Comment by maktak1995** [comment]
まずはデザインを見せてDstメンにユーザーヒアリングする

**Comment by noronaoki** [comment]
@maktak1995 
とりあえずプロトタイプ作ったんだけど、XDの都合上うまく表現できない部分もあるんで口頭で説明しますね

**Comment by maktak1995** [comment]
## プロトタイプの動作補足説明
### キーボード入力
  * 必要な桁数入力されたら自動で隣にフォーカスが移動する
  * Enter押下でも同じ挙動
### カレンダー入力
  * カレンダー左上に同様の入力欄
  * カレンダーは縦スクロール
  * スティッキーな日付表示はスクロールすると月が切り替わる
  * クリックすると各月へのショートカットが表示される 

* 縦スクロールなのは一般的に横スクロールはしづらいものだから

**Comment by maktak1995** [comment]
仕様Doc: https://docs.google.com/document/d/1xCYGOcgtyQfXsAi0Tv_OW1XrdkyDqE8f2hBI87uRIbc/edit#

**Comment by maktak1995** [comment]
## 背景の整理
今回のタスクは複数のやりたいことが絡まっているのでそれを解きほぐした上でタスクをブレイクダウンしたい

### momentjs を除去したい
* 公式がサポート終了するから
### React-dates を除去したい
* momentjs に依存しているライブラリだから
* 更新が滞っており react v18 への対応が見込めないから
### DateRangePicker のデザインをリニューアルしたい
* 現状のデザインは仮のもの
* ちゃんとしたデザイン案に沿ったものとしたい 

## 目的
### 1. momentjs と react-dates を剥がす
* 現実的な候補として dayjs がある
  * interface が momentjs と同じなので置換をやりやすい
  * 様々なライブラリ候補のなかで一番小さい
* dayjs であれば react-dates の置換先として dayjs ネイティブなものではなくても momentjs 用のライブラリをfolkして置き換えて使うという選択肢も出てくる
* ステップ2を考慮したライブラリでまずはそのままの置換をすすめる？
### 2. DateRangePicker のデザインを変更する
* デザインと仕様はすでに固まっている
* いいライブラリがなければフルスクラッチもありうるが、難易度は跳ね上がる
* [spectrum](https://react-spectrum.adobe.com/blog/date-and-time-pickers-for-all.html) など参考になりそうな実装はある

**Comment by maktak1995** [comment]
muiのdateRangePickerがdayjs使っててUIがreact-datesと同じなので最初の置き換えにはいいかもしれない
https://mui.com/x/react-date-pickers/date-range-picker/

**Comment by maktak1995** [comment]
最初のステップとしてmuiを使った置き換えを検討したが、muiのDateRangePickerは有料版限定のコンポーネントであった。
なのでアウト。

**Comment by maktak1995** [comment]
## 他の置き換え候補

### react-suite DateRangePicker
* 更新が活発でReact v18への対応も進んでいる
* 中華製で他に比べると利用率は高くない
* デザインシステム全部をインストールする必要があるためバンドルの肥大化が懸念される

### daterangepicker-dayjs
* momentjsを利用したdaterangepickerを個人でフォークしてdayjsに対応させたもの。
* jqueryを使用しておりレガシーな実装
* Reactでの利用は考慮されていない
* 更新が1年前で止まっている

**Comment by maktak1995** [comment]
date-fns だと [react-date-range](https://www.npmjs.com/package/react-date-range) といういい感じのライブラリがある

**Comment by maktak1995** [comment]
## 案1: react-suite をインストールして使用する
* 活発なライブラリなので安定した利用が見込める
* ライブラリのコンポーネント全部インストールしないといけないのでバンドルが肥大化する

## 案2: react-date-range を使う
* かなり柔軟なライブラリなので今後来る新しいデザインにもそのまま使い回せるかも
* dayjsでもmomentjsでもないのでingred-uiを導入しているプロダクト側の大規模な対応が必要になる

## 案3: react-datesをフォークしてきてdayjsとReact18に対応できるよう大改修を加えて使う
* ぱっとコードを見た感じそこまで難しいことでもまあなさそう
* 完全に自分たちで管理することにはなる
* うまくいけばingred-ui側の変更を最小限にして置き換えることが可能になる

**Comment by maktak1995** [comment]
案3かなー
結局デザインは(いつ変えるかはわからないが) あとから変わるんだし、応急手当的な処理でもまあいいんじゃないか、という気はする

**Comment by maktak1995** [comment]
いろいろしてみたがやっぱりreact-datesの手直しは全体的に古くなってるせいで余計に難しく、現実的ではなかった
date-fnsであれば使えるライブラリがいくつか存在しているので、移行先をdayjsからdate-fnsに変えられないか、変えた場合はどんな影響が出るのかを調査して可能そうであればdate-fnsに変える方向に倒したい。

**Comment by maktak1995** [comment]
@takurinton がdayjsでのカレンダー自作の検証をしてくれた。良さそうなので最終的にはdayjsでフルスクラッチする方針とする。
https://dev.takurinton.com/tech/frontend/calender-ui-prototype.html
https://github.com/takurinton/calender/pull/2

**Comment by maktak1995** [comment]
最終的な実装方針は以下の通り。
1. react-dates の moment.js の部分を dayjs に変換するラッパーを作る
2. 一旦リリースして各プロダクト置き換え
3. 置き換えてる間に新しいカレンダーをフルスクラッチ + dayjs で実装
4. なんかこれ用のリリースブランチ（v11.0.0-beta-1 とか）作るか、コンポーネントの名前を <DatePickerNext /> とかに変えて試験運用してみる
5. 良さそうだったらいよいよ置き換え

**Comment by youchann** [comment]
@maktak1995 

どのように引き継いだのかを書いておいてもらえると:pray:

**Comment by takurinton** [comment]
- [ ] Calendar コンポーネントの追加
- [ ] DateField コンポーネントの追加
- [ ] DatePicker の追加
- [ ] CalendarRange コンポーネントの追加
- [ ] DateRangeField コンポーネントの追加
- [ ] DateRangePicker コンポーネントの追加
- [ ] スタイルの細かい修正
- [ ] インターフェイスの整理

**Comment by takurinton** [comment]
snapshot テストは style やインターフェイス調整するタイミングで入れる

**Comment by takurinton** [comment]
ここまでやってきたこと

* issues
  * https://github.com/voyagegroup/ingred-ui/issues/975
  * https://github.com/voyagegroup/ingred-ui/issues/871
  * https://github.com/voyagegroup/ingred-ui/issues/856
* pr
  * https://github.com/voyagegroup/ingred-ui/pull/1080
* prototype
  * https://github.com/takurinton/dateinput
  * https://github.com/takurinton/calendar （微調整ののち採用）
  * https://github.com/takurinton/datepicker-integration
  * https://github.com/takurinton/date （採用）
* playground: https://datepicker-integration.vercel.app/
* memo
  * https://memo.takur.in/tech/frontend/calender-ui-prototype.html
  * https://memo.takur.in/tech/frontend/calender-ui-prototype-with-scroll.html
  * https://memo.takur.in/tech/frontend/calender-ui-prototype-with-scroll-performance-improvement.html
  * https://memo.takur.in/tech/frontend/dateinput-components.html
  * https://memo.takur.in/tech/frontend/datefield.html

細かいデザインやドキュメントは社外向けに書いてないので一旦載せない。後で整理して出す。

**Comment by takurinton** [comment]
DateRangeField について
現状だと format prop は1つしか渡すことができず、開始日と終了日に共通のフォオーマットを当てる形にしてるけど、それぞれ独立させたいケースがあるかもしれない。
![image](https://github.com/voyagegroup/ingred-ui/assets/50351271/89aed1fa-0261-4744-8234-3974e8280362)

例として、広告の配信期間を指定する際

- 開始日時は `HH時00分00秒` を指定したい
- 終了日時は `HH時59分59秒` を指定したい

みたいなケースがありそうで、それを format で縛ろうとするとそれぞれ独立していた方がやりやすい

**Comment by takurinton** [comment]
date prop に null を含めるかどうか検討したい。
ユースケースを見る限り、null を入れたいケースはありそう（終了日時を指定せずに submit する時など）

また、date が `Dayjs | null` になるのであれば onDateChange は `(newDate: Dayjs | null) => void` になるべき。

**Comment by takurinton** [comment]
思慮が浅かった、dayjs 自体が null を返してくる可能性があるのか...。

**Comment by takurinton** [comment]
既知のバグとしてこれがある
https://github.com/voyagegroup/ingred-ui/pull/1367#pullrequestreview-1579729227

**Comment by takurinton** [comment]
TODO
カレンダーを閉じる用のバツボタンを実装していないのでする

**Comment by takurinton** [comment]
DateRangePicker、Actions が多重定義されてる。
後で修正する。

**Comment by takurinton** [comment]
インターフェイスの整理をする。
それぞれのコンポーネントに以下の props を追加する。

- DatePicker/DateRangePicker
  - errorText
  - disable
  - isOutsideRange
- Calendar/CalendarRange
  - isOutsideRange
- DateField/DateRangeField
  - errorText
  - disable

**Comment by takurinton** [comment]
年選択のスクロールについてやる。
これは

- useIntersection の定義
- カレンダーの無限スクロールを担っている useScroll を useScrollCalendar にリネーム、IntersectionObserver の部分は useIntersection を使う
- 年選択の無限スクロールを担う useScrollYear を追加、IntersectionObserver の部分は useIntersection を使う

という流れでやる。

**Comment by takurinton** [comment]
年選択のスクロールの前に一旦リリースかけてもいいかもな。プロダクト側で使う期間が欲しい。
最低限のインターフェイスさえ揃えば問題なく使えるので（現在追加してるインターフェイスはプロダクト側のコードをベースに定義してるので特段困らないはず）

**Comment by takurinton** [comment]
memo
`errorText` prop の必要性とデザインを野呂さんに確認する。
https://github.com/voyagegroup/ingred-ui/pull/1377#issuecomment-1687238377

**Comment by takurinton** [comment]
デザインレビューと擦り合わせをした。
出てきた課題のメモ。https://cartaholdings.slack.com/archives/C02Q8F3FQBC/p1693276818915679

- カレンダー開いたらフォーカス？の青い線が出てる
  - タイミングがよくわからない
  - 消していい
- 閉じるボタンの色を basic[900] にする
- 閉じるボタンの余白は16pxに
- 白に統一感がないので、合わせる
  - 真っ白に合わせる
  - theme.palette.background.default かな？
- calendar の外枠は border ではなく dropshadow にする
- calendar  の曜日部分は theme.gray.deepDark を使う
- 年月選択の hover を追加する
  - 四角に少し角丸をつける（actions のイメージが近い）
  - 色は水色
  - actions の背景も水色にする
- disable の calendar icon は日付と同じ色
- disable の calendar icon は disable にする
- is outside range の hover はなし（できたら）
- date range picker の日付 hover をした時の色を水色に修正
- date range picker の storybook、with actions に今日はいらない
- calendar icon は theme.palette.primary.main にする
- 英語対応も視野に入れる

**Comment by takurinton** [comment]
v14.6.0 としてリリースした。https://github.com/voyagegroup/ingred-ui/releases/tag/v14.6.0

**Comment by takurinton** [comment]
i18n 対応を v14.7.0 として出す

**Comment by takurinton** [comment]
v14.7.0 としてリリースした
https://github.com/voyagegroup/ingred-ui/releases/tag/v14.7.0

**Comment by takurinton** [comment]
v15 リリースしたらこの issue はとじる。
v15 は各プロダクトで適用してしばらく運用してから出すつもりで、その間にバグ等が発生したら都度回収する。

**Comment by takurinton** [comment]
日付を選択すると、カレンダーが viewport の先頭に行ってしまう問題を修正する

**Comment by takurinton** [comment]
React v17 以下でスクロール周りの不備が見つかった。そのため、ingred-ui を使ってる全てのプロダクトを React v18 に引き上げた。

**Comment by takurinton** [comment]
memo
Action の部分の max-width を 130px にする。
溢れた部分は3点リーダーで省略

**Comment by takurinton** [comment]
memo
Actions の部分が縦に溢れたら、スクロール可能な領域にする

**Comment by takurinton** [comment]
そろそろデザインの修正も落ち着いてきたし、snapshot テスト追加してもいいかもしれない

**Comment by takurinton** [comment]
memo
Actions とカレンダーを分けてる線の色を Basic[200] に修正する

**Comment by takurinton** [comment]
DateRangeField、今だと Input を2つ横並びにしておいてるけど、せっかく format の仕組み作ったので1つの Input で賄えるようにしたい。
開始日と終了日を判定するロジックを考えてないのですぐできるものではないけど、そのほうが利便性が高まるのは自明なので取り組むぞー
https://ingred-ui.netlify.app/?path=/story/components-inputs-daterangefield--example

**Comment by takurinton** [comment]
一旦一区切り
https://github.com/voyagegroup/ingred-ui/pull/1462
