### ISSUE TITLE
changeset の導入

### ISSUE THREAD

**Issue by takurinton** [voyagegroup/ingred-ui#985]
バージョン管理を changeset でやりたい。
理由は以下。

- ingred-ui は週1回、抽選で当たった誰かがリリースを行うからセマンティックバージョニングでどのバージョンをあげればいいかがわからない
  - 全部のPRを見てバージョニングを判断するのは結構厳しい
  - 変更がないからスルーする週とかがあると、2週分見ないといけない
  - merge するたびに changeset がリリースノートを作ってくれると嬉しい
  - そのリリースノートだけ確認して実際のリリースをすればいいのでいい感じになる
- バージョンの入力で事故る
  - 今バージョンは Actions の部分でリリースワークフローを選択して手打ちしている
  - 以前、事故ったことがある
  - 手入力は避けて、CLI でバージョニングができると嬉しい

**Comment by takurinton** [comment]
dependabot の対応とかどうすればいいのか、モノレポじゃないけど特性として正しいのか等はまだ判断できるほど深く追えてないので、調べつつこの issue にメモっていく。

**Comment by takurinton** [comment]
Preact とかは changeset を導入してる

**Comment by takurinton** [comment]
https://github.com/changesets/action#with-publishing

**Comment by penicillin0** [comment]
> モノレポじゃないけど特性として正しいのか

シングルレポでも有用だよっていう説明

> Changesets are designed first and foremost to handle versioning in multi-package repos, where interdependencies flowing through the system are important to understand and capture.
> 
> Conceptually though, the benefits of changesets are detachable from this. I think this process overall leads to an improvement in Pull Requests that helps increase confidence in versioning decisions and changelog entries.
( https://github.com/changesets/changesets/blob/main/docs/detailed-explanation.md#benefits-to-single-package-repos )

良さそう

**Comment by penicillin0** [comment]
https://github.com/changesets/changesets#integrating-with-ci

changesetsがいないときはCIが落ちるように

[998592f](https://github.com/voyagegroup/ingred-ui/pull/1298/commits/998592fff4bb318b95809d507d84715e4655ad0f)

**Comment by penicillin0** [comment]
for dependabot

https://github.com/backstage/backstage/blob/master/.github/workflows/sync_dependabot-changesets.yml
