### ISSUE TITLE
`typing.d.ts` の `React.StatelessComponent` を `React.FunctionComponent` にする

### ISSUE THREAD

**Issue by takurinton** [voyagegroup/ingred-ui#987]
現在削除済みの StatelessComponent が typing.d.ts で使われてるので、置き換えたい。
https://github.com/voyagegroup/ingred-ui/blob/master/src/typings.d.ts#L10

```ts
// typing.d.ts
// 名前空間 'React' にエクスポートされたメンバー 'StatelessComponent' がありません。ts(2694)
type SvgrComponent = {} & React.StatelessComponent<
  React.SVGAttributes<SVGElement>
>;
```

![image](https://user-images.githubusercontent.com/50351271/190139218-41106286-fcae-4371-8f6f-3f2d6538bb6e.png)

**Comment by takurinton** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56399

**Comment by penicillin0** [comment]
deprecatedになったのこの辺から
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30364

> The motivation for this is twofold: firstly the addition of hooks means function components can have state, and secondly the term "stateless component" can equally apply to class components which don't use any state, causing some confusion

以下の理由から混乱を解消するために名前を変更
1. hooksの登場で状態を持てるようになった
2. クラスコンポーネントにも`StatelessComponent`が使えてしまう

**Comment by penicillin0** [comment]
なんとなくmui
https://github.com/mui/material-ui-pickers/issues/2056

色々調べようとしましたが、そもそもエイリアスでしかなくあまり論点なさそうなので、タイトルまま変更して良さそうです。

**Comment by takurinton** [comment]
なるほど、ここらへんのコメントが今の実装になってるのか
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30364#issuecomment-437160778
